### PR TITLE
CanUseItems() update

### PR DESCRIPTION
**Pull request by IdcNoob**
Removed
"modifier_sheepstick_debuff"
Added !IsHexed

Removed
"modifier_tusk_snowball_movement_friendly"
"modifier_enigma_black_hole_pull"
Already checked by IsStunned (but not "modifier_tusk_snowball_movement")

Added
"modifier_axe_berserkers_call"
"modifier_phoenix_supernova_hiding"

### CODE REVIEW

**Comment by Moones** [comment]
Can you try if IsRooted() covers any of these modifiers as well ?

**Comment by Sophylax** [comment]
Why? Even if it does, root doesn't block item usages (except blink dagger I suppose).

**Comment by IdcNoob** [comment]
And u wont be able to cast dagger for 3 sec after any root i guess.

**Comment by Moones** [comment]
You are right Sophylax. :+1:

**Comment by Sophylax** [comment]
> And u wont be able to cast dagger for 3 sec after any root i guess.

Nope, If you don't get damaged in the root you will be able to cast it instantly after the root. Root just prevents some abilities from being casted. Damage puts the blink on cooldown. Some roots that damage can exhibit this property but otherwise they are seperate.

**Pull request merged**
