### PR TITLE
IsInvul() update

### PR DESCRIPTION
**Pull request by IdcNoob**
WK aghanim ult is not checked by UnitState.Invulnerable.

### CODE REVIEW

**Comment by Moones** [comment]
Are you sure it grants Invulnerability? I think you just cant die but you are not invurnerable.
I guess we gotta port CanDie() from the old Utils.lua and add check to the method.

**Comment by IdcNoob** [comment]
Well, i guess it doesnt grants u invul like ember fist.
But when even axe cant kill u, then this check should be some where.

**Comment by Moones** [comment]
Yes as I said, we can port the CanDie() and add check for this modifier!

**Comment by Sophylax** [comment]
Invulnerable units are not susceptible to disables. most spells will not even interact with them. You can easily disable death delayed wraiths. The effect is more fitting for CanDie() for it acts like a shallow grave that kills you in the end and as you noted axe cannot bypass. But since the units will die after the modifier ends even CanDie() is a weird place for this modifier, however placing it there is probably the best as behaviour against death delayed wraiths should be very similar to behaviour against enemies who cannot die.

**Comment by Moones** [comment]
The CanDie() method is now added.

**Pull request closed without merging**
